import localFont from "next/font/local";
import { headers } from 'next/headers'
import { Providers } from "@/app/lib/providers";
import { cookieToInitialState } from 'wagmi'
import { config } from '@/app/lib/wagmi'
import "./assets/styles/globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const initialState = cookieToInitialState(
    config,
    headers().get('cookie'),
  )
  return (
    <html lang="en">
      <body className={`antialiased bg-black`}>

        <Providers initialState={initialState}>
          <Navbar />
          {children}
          <Footer />
        </Providers>

      </body>
    </html>
  );
}
